imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:       rotating_file
            max_files:  3
            path:       "%kernel.logs_dir%/%kernel.environment%.log"
            level:      debug

        # Gesdon specifical log : save log into dedicated file
        gesdon:
            type:           rotating_file
            max_files:      30
            path:           %kernel.logs_dir%/%kernel.environment%.gesdon.log
            level:          debug
            channels:       gesdon

        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]

        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]

assetic:
    use_controller: true

swiftmailer:
    delivery_address: %delivery_address%
