parameters:
    max_items_per_page: 50

imports:
    - { resource: services/forms.yml }
    - { resource: services/managers.yml }
    - { resource: services/repositories.yml }
    - { resource: services/twig.yml }

services:
    paginator:
        class: AppBundle\Tools\Paginator
        arguments: ["@router", %max_items_per_page%]