services:
    form.type.address:
        class: AppBundle\Form\AddressType
        tags:
            - { name: form.type, alias: address }

    form.type.contributor:
        class: AppBundle\Form\ContributorType
        tags:
            - { name: form.type, alias: contributor }

    form.type.donation:
        class: AppBundle\Form\DonationType
        tags:
            - { name: form.type, alias: donation }

    form.type.donation.delete:
        class: AppBundle\Form\DonationDeleteType
        tags:
            - { name: form.type, alias: donation_delete }

    form.type.configuration_item:
        class: AppBundle\Form\ConfigurationItemType
        tags:
            - { name: form.type, alias: configuration_item }

    form.type.configuration:
        class: AppBundle\Form\ConfigurationType
        tags:
            - { name: form.type, alias: configuration }

    form.type.contributor_type:
        class: AppBundle\Form\ContributorTypeType
        tags:
            - { name: form.type, alias: contributor_type }

    form.type.contributor_type.delete:
        class: AppBundle\Form\ContributorTypeDeleteType
        tags:
            - { name: form.type, alias: contributor_type_delete }

    form.type.payment_type:
        class: AppBundle\Form\PaymentTypeType
        tags:
            - { name: form.type, alias: payment_type }

    form.type.payment_type.delete:
        class: AppBundle\Form\PaymentTypeDeleteType
        tags:
            - { name: form.type, alias: payment_type_delete }
