services:
    manager.donation:
        class: AppBundle\Manager\Donation
        arguments:
            - @doctrine.orm.entity_manager
            - @repository.donation
            - @repository.contributor
            - @repository.address
            - @session.flash_bag

    manager.configuration:
        class: AppBundle\Manager\Configuration
        arguments:
            - @doctrine.orm.entity_manager
            - @repository.configuration

    manager.receipt:
        class: AppBundle\Manager\Receipt
        arguments:
            - @doctrine.orm.entity_manager
            - @logger
            - @repository.donation
            - @manager.configuration
        tags:
            - { name: monolog.logger, channel: gesdon }
