services:
    repository.address:
        class: AppBundle\Repository\AddressRepository
        public: true
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle:Address ]

    repository.configuration:
        class: AppBundle\Repository\ConfigurationRepository
        public: false
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle:Configuration ]

    repository.contributor:
        class: AppBundle\Repository\ContributorRepository
        public: true
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle:Contributor ]

    repository.donation:
        class: AppBundle\Repository\DonationRepository
        public: true
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle:Donation ]

    repository.receipt:
        class: Doctrine\ORM\EntityRepository
        public: true
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AppBundle:Receipt ]
